// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaSimulator.Server.Infrastructure.Persistence;

#nullable disable

namespace SocialMediaSimulator.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901145613_AddNewsSystem")]
    partial class AddNewsSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AccountBelief", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountBeliefId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Belief")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FormedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfluenceSource")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RumorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountBeliefId")
                        .IsUnique();

                    b.HasIndex("RumorId");

                    b.HasIndex("AccountId", "RumorId")
                        .IsUnique();

                    b.ToTable("AccountBeliefs", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AccountHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AccountHistory", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AiProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("AiProviderConfigs", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockerAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockedAccountId");

                    b.HasIndex("BlockerAccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("BlockerAccountId", "BlockedAccountId")
                        .IsUnique();

                    b.ToTable("Blocks", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.CausalChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CausalChainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CauseDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CauseEventId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CauseStrength")
                        .HasColumnType("REAL");

                    b.Property<int>("CauseType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CauseEventId");

                    b.HasIndex("EventId");

                    b.ToTable("CausalChain", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAccountId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.HasIndex("Status");

                    b.HasIndex("PostId", "CreatedAt");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MemberCount");

                    b.HasIndex("OwnerAccountId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Topic");

                    b.HasIndex("TopicId");

                    b.ToTable("Communities", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.CommunityMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "IsActive");

                    b.HasIndex("CommunityId", "AccountId")
                        .IsUnique();

                    b.HasIndex("CommunityId", "IsActive");

                    b.ToTable("CommunityMemberships", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChainDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DramaLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventChainId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<double>("FollowUpProbability")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NarrativeArcLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NarrativeContext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Popularity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TriggerEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatorAccountId");

                    b.HasIndex("EventChainId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentEventId");

                    b.HasIndex("Topic");

                    b.HasIndex("TriggerEventId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.EventConsequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventConsequenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasExecuted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("Type");

                    b.ToTable("EventConsequences", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.EventParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContributionScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventParticipationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LLMReasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EventId", "AccountId");

                    b.ToTable("EventParticipations", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.FeedImpression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Clicked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Commented")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Liked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<bool>("Shared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Skipped")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.HasIndex("AccountId", "CreatedAt");

                    b.HasIndex("AccountId", "PostId");

                    b.ToTable("FeedImpressions", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FollowedAccountId");

                    b.HasIndex("FollowerAccountId");

                    b.HasIndex("FollowerAccountId", "FollowedAccountId")
                        .IsUnique();

                    b.ToTable("Follows", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Hashtag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HashtagId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TodayUsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrendingRank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TrendingSince")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsTrending");

                    b.HasIndex("NormalizedTag")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.HasIndex("TodayUsageCount");

                    b.HasIndex("TopicId");

                    b.ToTable("Hashtags", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Mute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MutedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuterAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MutedAccountId");

                    b.HasIndex("MuterAccountId");

                    b.HasIndex("MuterAccountId", "MutedAccountId")
                        .IsUnique();

                    b.ToTable("Mutes", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccuracyRating")
                        .HasColumnType("REAL");

                    b.Property<int>("ArticlesPublished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BreakingNewsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredibilityScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NewsAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsBio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsTagline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalArticleViews")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("NewsAccountId")
                        .IsUnique();

                    b.ToTable("NewsAccounts", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakingNewsBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CoveredEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CoveredRumorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CoveredTopicId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoveredTopicId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBreakingNews")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MentionedAccountsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NewsAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedPostId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .IsUnique();

                    b.HasIndex("Category");

                    b.HasIndex("CoveredTopicId1");

                    b.HasIndex("IsBreakingNews");

                    b.HasIndex("NewsAccountId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Status");

                    b.ToTable("NewsArticles", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsExposure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExposedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExposureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("ExposureId")
                        .IsUnique();

                    b.ToTable("NewsExposures", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipientAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RelatedPostGuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("RelatedPostId");

                    b.HasIndex("RecipientAccountId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("RecipientAccountId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAccountId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPostId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpcProfileId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetPostId");

                    b.HasIndex("Executed", "ScheduledAt");

                    b.ToTable("NpcActions", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterestKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InterestKey");

                    b.HasIndex("NpcProfileId", "InterestKey")
                        .IsUnique();

                    b.ToTable("NpcInterests", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcPersonality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Agreeableness")
                        .HasColumnType("REAL");

                    b.Property<double>("Conscientiousness")
                        .HasColumnType("REAL");

                    b.Property<double>("Extraversion")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Neuroticism")
                        .HasColumnType("REAL");

                    b.Property<int>("NpcProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Openness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NpcProfileId")
                        .IsUnique();

                    b.ToTable("NpcPersonalities", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSimulatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextSimulationAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("NextSimulationAt");

                    b.HasIndex("NpcId")
                        .IsUnique();

                    b.HasIndex("IsActive", "NextSimulationAt");

                    b.ToTable("NpcProfiles", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.OfflineSimulationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatchupSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventsSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowersGained")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowersLost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OfflineSimulationResultId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicksSimulated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("AccountId", "IsAcknowledged");

                    b.ToTable("OfflineSimulationResults", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PersistenceTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("PersistenceTests", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAccountId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Topic");

                    b.HasIndex("AuthorAccountId", "CreatedAt");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId", "AccountId")
                        .IsUnique();

                    b.ToTable("PostLikes", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PostVirality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ControversyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstViralThresholdCrossed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasControversyAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MassivelyViralAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("PeakVelocity")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostViralityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reach")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("ShareCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEngagement")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Velocity")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ViralAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.HasIndex("Score");

                    b.HasIndex("State");

                    b.HasIndex("Velocity");

                    b.ToTable("PostVirality", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<float>("FameLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Rumor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNotable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PeakVelocity")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PeakedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RumorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShareCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourcePostId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpreadByCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpreadType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TruthStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("OriginAccountId");

                    b.HasIndex("RumorId")
                        .IsUnique();

                    b.HasIndex("SourcePostId");

                    b.HasIndex("TruthStatus");

                    b.ToTable("Rumors", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.RumorEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredibilityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RumorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsRumor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EvidenceId")
                        .IsUnique();

                    b.HasIndex("RumorId");

                    b.ToTable("RumorEvidence", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivePostCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriberCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.TopicSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TopicId")
                        .IsUnique();

                    b.ToTable("TopicSubscriptions", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Trend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EngagementTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HashtagId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PeakedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrendId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniquePosters")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Velocity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("HashtagId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Query");

                    b.HasIndex("Rank");

                    b.HasIndex("Scope");

                    b.HasIndex("Strength");

                    b.HasIndex("TopicId");

                    b.ToTable("Trends", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.TrendPropagation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromCommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PropagatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropagationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToCommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrendId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromCommunityId");

                    b.HasIndex("ToCommunityId");

                    b.HasIndex("TrendId");

                    b.ToTable("TrendPropagations", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.ViralityTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngagementAtTransition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<float>("ScoreAtTransition")
                        .HasColumnType("REAL");

                    b.Property<int>("ToState")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransitionedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("VelocityAtTransition")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TransitionedAt");

                    b.HasIndex("PostId", "TransitionedAt");

                    b.ToTable("ViralityTransition", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AccountBelief", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Rumor", "Rumor")
                        .WithMany("Beliefs")
                        .HasForeignKey("RumorId")
                        .HasPrincipalKey("RumorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Rumor");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AccountHistory", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany("History")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Block", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "BlockedAccount")
                        .WithMany()
                        .HasForeignKey("BlockedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "BlockerAccount")
                        .WithMany()
                        .HasForeignKey("BlockerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedAccount");

                    b.Navigation("BlockerAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.CausalChain", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Event", "CauseEvent")
                        .WithMany()
                        .HasForeignKey("CauseEventId")
                        .HasPrincipalKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .HasPrincipalKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("CauseEvent");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Comment", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "AuthorAccount")
                        .WithMany()
                        .HasForeignKey("AuthorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorAccount");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Community", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Topic", null)
                        .WithMany("Communities")
                        .HasForeignKey("TopicId");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.CommunityMembership", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "Community")
                        .WithMany("Memberships")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Event", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "CreatorAccount")
                        .WithMany()
                        .HasForeignKey("CreatorAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("CreatorAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.EventConsequence", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.EventParticipation", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Event", "Event")
                        .WithMany("Participations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.FeedImpression", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Follow", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "FollowedAccount")
                        .WithMany()
                        .HasForeignKey("FollowedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "FollowerAccount")
                        .WithMany()
                        .HasForeignKey("FollowerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedAccount");

                    b.Navigation("FollowerAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Hashtag", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Topic", "Topic")
                        .WithMany("Hashtags")
                        .HasForeignKey("TopicId")
                        .HasPrincipalKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Mute", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "MutedAccount")
                        .WithMany()
                        .HasForeignKey("MutedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "MuterAccount")
                        .WithMany()
                        .HasForeignKey("MuterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MutedAccount");

                    b.Navigation("MuterAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsAccount", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Topic", "CoveredTopic")
                        .WithMany()
                        .HasForeignKey("CoveredTopicId1");

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NewsAccount", "NewsAccount")
                        .WithMany("Articles")
                        .HasForeignKey("NewsAccountId")
                        .HasPrincipalKey("NewsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoveredTopic");

                    b.Navigation("NewsAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsExposure", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NewsArticle", "Article")
                        .WithMany("Exposures")
                        .HasForeignKey("ArticleId")
                        .HasPrincipalKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "ActorAccount")
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "RecipientAccount")
                        .WithMany()
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "RelatedPost")
                        .WithMany()
                        .HasForeignKey("RelatedPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorAccount");

                    b.Navigation("RecipientAccount");

                    b.Navigation("RelatedPost");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcAction", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "NpcProfile")
                        .WithMany()
                        .HasForeignKey("NpcProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcProfile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcInterest", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "NpcProfile")
                        .WithMany("Interests")
                        .HasForeignKey("NpcProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcProfile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcPersonality", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "NpcProfile")
                        .WithOne("Personality")
                        .HasForeignKey("SocialMediaSimulator.Server.Domain.Entities.NpcPersonality", "NpcProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcProfile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithOne("NpcProfile")
                        .HasForeignKey("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.OfflineSimulationResult", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Post", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "AuthorAccount")
                        .WithMany()
                        .HasForeignKey("AuthorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuthorAccount");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PostLike", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PostVirality", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .HasPrincipalKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Profile", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("SocialMediaSimulator.Server.Domain.Entities.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Rumor", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "OriginAccount")
                        .WithMany()
                        .HasForeignKey("OriginAccountId");

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "SourcePost")
                        .WithMany()
                        .HasForeignKey("SourcePostId")
                        .HasPrincipalKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("OriginAccount");

                    b.Navigation("SourcePost");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.RumorEvidence", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Rumor", "Rumor")
                        .WithMany("Evidence")
                        .HasForeignKey("RumorId")
                        .HasPrincipalKey("RumorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Rumor");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Trend", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Hashtag", "Hashtag")
                        .WithMany()
                        .HasForeignKey("HashtagId")
                        .HasPrincipalKey("HashtagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .HasPrincipalKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Community");

                    b.Navigation("Hashtag");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.TrendPropagation", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "FromCommunity")
                        .WithMany()
                        .HasForeignKey("FromCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Community", "ToCommunity")
                        .WithMany()
                        .HasForeignKey("ToCommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Trend", "Trend")
                        .WithMany()
                        .HasForeignKey("TrendId")
                        .HasPrincipalKey("TrendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCommunity");

                    b.Navigation("ToCommunity");

                    b.Navigation("Trend");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.ViralityTransition", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .HasPrincipalKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Account", b =>
                {
                    b.Navigation("History");

                    b.Navigation("NpcProfile");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Community", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Event", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsAccount", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NewsArticle", b =>
                {
                    b.Navigation("Exposures");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Personality");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Rumor", b =>
                {
                    b.Navigation("Beliefs");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Communities");

                    b.Navigation("Hashtags");
                });
#pragma warning restore 612, 618
        }
    }
}
