// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaSimulator.Server.Infrastructure.Persistence;

#nullable disable

namespace SocialMediaSimulator.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901054056_AddNpcSimulation")]
    partial class AddNpcSimulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AccountHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AccountHistory", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockerAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockedAccountId");

                    b.HasIndex("BlockerAccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("BlockerAccountId", "BlockedAccountId")
                        .IsUnique();

                    b.ToTable("Blocks", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAccountId");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("PostId");

                    b.HasIndex("Status");

                    b.HasIndex("PostId", "CreatedAt");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FollowedAccountId");

                    b.HasIndex("FollowerAccountId");

                    b.HasIndex("FollowerAccountId", "FollowedAccountId")
                        .IsUnique();

                    b.ToTable("Follows", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Mute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MutedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuterAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MutedAccountId");

                    b.HasIndex("MuterAccountId");

                    b.HasIndex("MuterAccountId", "MutedAccountId")
                        .IsUnique();

                    b.ToTable("Mutes", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Executed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAccountId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPostId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpcProfileId");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("TargetPostId");

                    b.HasIndex("Executed", "ScheduledAt");

                    b.ToTable("NpcActions", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterestKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NpcProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Strength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InterestKey");

                    b.HasIndex("NpcProfileId", "InterestKey")
                        .IsUnique();

                    b.ToTable("NpcInterests", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcPersonality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Agreeableness")
                        .HasColumnType("REAL");

                    b.Property<double>("Conscientiousness")
                        .HasColumnType("REAL");

                    b.Property<double>("Extraversion")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Neuroticism")
                        .HasColumnType("REAL");

                    b.Property<int>("NpcProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Openness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NpcProfileId")
                        .IsUnique();

                    b.ToTable("NpcPersonalities", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSimulatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextSimulationAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("NextSimulationAt");

                    b.HasIndex("NpcId")
                        .IsUnique();

                    b.HasIndex("IsActive", "NextSimulationAt");

                    b.ToTable("NpcProfiles", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PersistenceTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("PersistenceTests", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorAccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("AuthorAccountId", "CreatedAt");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId");

                    b.HasIndex("PostId", "AccountId")
                        .IsUnique();

                    b.ToTable("PostLikes", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.AccountHistory", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany("History")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Block", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "BlockedAccount")
                        .WithMany()
                        .HasForeignKey("BlockedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "BlockerAccount")
                        .WithMany()
                        .HasForeignKey("BlockerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedAccount");

                    b.Navigation("BlockerAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Comment", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "AuthorAccount")
                        .WithMany()
                        .HasForeignKey("AuthorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorAccount");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Follow", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "FollowedAccount")
                        .WithMany()
                        .HasForeignKey("FollowedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "FollowerAccount")
                        .WithMany()
                        .HasForeignKey("FollowerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowedAccount");

                    b.Navigation("FollowerAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Mute", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "MutedAccount")
                        .WithMany()
                        .HasForeignKey("MutedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "MuterAccount")
                        .WithMany()
                        .HasForeignKey("MuterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MutedAccount");

                    b.Navigation("MuterAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcAction", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "NpcProfile")
                        .WithMany()
                        .HasForeignKey("NpcProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcProfile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcInterest", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "NpcProfile")
                        .WithMany("Interests")
                        .HasForeignKey("NpcProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcProfile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcPersonality", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "NpcProfile")
                        .WithOne("Personality")
                        .HasForeignKey("SocialMediaSimulator.Server.Domain.Entities.NpcPersonality", "NpcProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcProfile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithOne("NpcProfile")
                        .HasForeignKey("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Post", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "AuthorAccount")
                        .WithMany()
                        .HasForeignKey("AuthorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorAccount");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.PostLike", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Profile", b =>
                {
                    b.HasOne("SocialMediaSimulator.Server.Domain.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("SocialMediaSimulator.Server.Domain.Entities.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Account", b =>
                {
                    b.Navigation("History");

                    b.Navigation("NpcProfile");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.NpcProfile", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Personality");
                });

            modelBuilder.Entity("SocialMediaSimulator.Server.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
